apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cloudcommerce
  labels:
    app: notification-service
    app.kubernetes.io/part-of: cloudcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        app.kubernetes.io/part-of: cloudcommerce
    spec:
      serviceAccountName: cloudcommerce-sa
      containers:
        - name: notification-service
          image: cloudcommerceacr.azurecr.io/notification-service:latest
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: PORT
              value: "3005"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cloudcommerce
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
      name: http
  selector:
    app: notification-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: cloudcommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  namespace: cloudcommerce
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: notification-service
